spring.application.name = SpringReport
spring.profiles.active = @profiles.active@
server.servlet.session.timeout = 86400
server.tomcat.uri-encoding=UTF-8
server.max-http-post-size=104857600
server.compression.enabled=true
server.compression.mime-types=application/javascript,text/css,application/json,application/xml,text/html,text/xml,text/plain
server.compression.min-response-size=2048

spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB
spring.http.encoding.charset=UTF-8
spring.http.encoding.force=true
spring.http.encoding.enabled=true
management.endpoints.web.exposure.include=*
management.metrics.tags.application=${spring.application.name}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.datasource.driver-class-name=org.postgresql.Driver
#spring.datasource.driver-class-name=dm.jdbc.driver.DmDriver
#spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
#spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
#spring.datasource.driver-class-name=com.kingbase8.Driver
#spring.datasource.driver-class-name=com.highgo.jdbc.Driver

spring.datasource.type=com.alibaba.druid.pool.DruidDataSource
# druid参数优化（可选）
# 初始化连接数
spring.datasource.initialSize=5
spring.datasource.minIdle=5
spring.datasource.maxActive=20
# 获取连接超时时间，默认 -1（无限等待）
spring.datasource.maxWait=60000
# 空闲连接检测线程的运行间隔时间，单位毫秒
spring.datasource.timeBetweenEvictionRunsMillis=60000
#  连接池中连接空闲多久后被驱逐（关闭），单位毫秒
spring.datasource.minEvictableIdleTimeMillis=300000
# 空闲时是否检测连接有效性
spring.datasource.testWhileIdle=true
spring.datasource.testOnBorrow=false
spring.datasource.testOnReturn=false
# 是否开启 PreparedStatement 缓存
spring.datasource.poolPreparedStatements=true
spring.datasource.maxPoolPreparedStatementPerConnectionSize=20
# 配置过滤器（多个用逗号分隔）
spring.datasource.filters=stat
# 控制连接池初始化时，initialSize 个连接是同步创建还是异步创建
spring.datasource.asyncInit=true
# mybatis-plus
mybatis-plus.type-aliases-package=com.springreport.entity
mybatis-plus.config-locations=classpath:mybatis/mybatis-config.xml
mybatis-plus.mapper-locations=classpath:mybatis/mapper/**/*.xml,classpath:extmapper/mapper/**/*.xml,classpath:slidemapper/mapper/**/*.xml,classpath:onlyofficemapper/mapper/**/*.xml
mybatis-plus.global-config.field-strategy=1
mybatis-plus.type-handlers-package=com.springreport.mybatishandler
mybatis-plus.configuration.jdbc-type-for-null=null
##pageHelper配置
pagehelper.helper-dialect=MYSQL
#pagehelper.helper-dialect=postgresql
#pagehelper.helper-dialect=oracle
#pagehelper.helper-dialect=sqlserver
pagehelper.reasonable=true
pagehelper.support-methods-arguments=true
pagehelper.params=count=countSql

# 邮箱配置
spring.mail.host=smtp.163.com
# 163邮箱
spring.mail.username=
# 注意这里不是邮箱密码，而是SMTP授权密
spring.mail.password=
spring.mail.port=465
spring.mail.protocol=smtps
spring.mail.default-encoding=UTF-8
spring.mail.from=

luckysheet.redis.channel=luckysheet.channel

org.quartz.jobStore.useProperties=true

#在集群中每个实例都必须有一个唯一的instanceId，但是应该有一个相同的instanceName
org.quartz.scheduler.instanceName=quartzScheduler
#Scheduler实例ID，全局唯一
org.quartz.scheduler.instanceId=AUTO
# 控制 Scheduler 的主调度线程是否为后台守护线程
org.quartz.scheduler.makeSchedulerThreadDaemon=true
# 获取触发器时是否需要在锁内执行
org.quartz.jobStore.acquireTriggersWithinLock = true

#Quartz 线程池配置
#Quartz 线程池类型
org.quartz.threadPool.class=org.quartz.simpl.SimpleThreadPool
#线程池大小
org.quartz.threadPool.threadCount=10
#线程池中线程的优先级
org.quartz.threadPool.threadPriority=5

#============================================================================
# Configure JobStore
#============================================================================
org.quartz.jobStore.class = org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.tablePrefix=QRTZ_
# 设置容忍度时长 单位毫秒
org.quartz.jobStore.misfireThreshold = 60000
# 配置数据源的名称，在后面配置数据源的时候要用到
# 例如org.quartz.dataSource.myDS.driver
org.quartz.jobStore.dataSource = myDS

# 集群配置
org.quartz.jobStore.isClustered = true
#只用于设置了isClustered为true的时候，设置一个频度（毫秒），用于实例报告给集群中的其他实例。
#这会影响到侦测失败实例的敏捷度。
org.quartz.jobStore.clusterCheckinInterval=5000
#这是JobStore能处理的错过触发的Trigger的最大数量。处理太多（2打）很快就会导致数据库表被锁定够长的时间，
#这样会妨碍别的（还未错过触发）trigger执行的性能。
org.quartz.jobStore.maxMisfiresToHandleAtATime=20

#多租户模式 1开启 2关闭
merchantmode=1
