<template>
  <div class="_tablepage">
    <searchForm
      :search-form="pageData.searchForm"
      :search-data="pageData.queryData"
      :search-handle="pageData.searchHandle"
      :table-handles="pageData.tableHandles"
    />
    <cusTable
      ref="custable"
      :is-selection="true"
      :is-index="true"
      :is-pagination="true"
      :is-handle="true"
      :loading="tableLoading"
      :table-cols="pageData.tableCols"
      :table-data="pageData.tableData"
      :table-page="pageData.tablePage"
      @handleCurrentChange="searchtablelist()"
      @selectChange="selectChange"
    />
    <modal
      ref="modalRef"
      :modal-config="pageData.modalConfig"
      :modal-form="pageData.modalForm"
      :modal-data="pageData.modalData"
      :modal-handles="pageData.modalHandles"
      @closeModal="closeModal()"
    />
    <modal
      ref="resultPropRef"
      :modal-config="pageData.resultPropModalConfig"
      :modal-form="pageData.resultPropModalForm"
      :modal-data="pageData.resultPropModalData"
      :modal-handles="pageData.resultPropModalHandles"
      @closeModal="closePropsModal()"
    />
    <modal
      ref="apiHeaderRef"
      :modal-config="pageData.apiHeaderModalConfig"
      :modal-form="pageData.apiHeaderModalForm"
      :modal-data="pageData.apiHeaderModalData"
      :modal-handles="pageData.apiHeaderModalHandles"
      @closeModal="closeHeadersModal()"
    />
  </div>
</template>
<script src="./ReportDatasource.js"></script>
